apiVersion: v1
kind: Service
metadata:
  name: my-load-balancer
spec:
  type: LoadBalancer
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  externalTrafficPolicy: Local
  loadBalancerIP: 10.0.0.100
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service-1
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  nodePort: 30001
---
apiVersion: v1
kind: Service
metadata:
  name: my-nodeport-service-2
spec:
  type: NodePort
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
  nodePort: 30002
---
apiVersion: v1
kind: Service
metadata:
  name: my-clusterip-service
spec:
  type: ClusterIP
  selector:
    app: my-app
  ports:
    - name: http
      port: 80
      targetPort: 8080
