apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx-deployment
  labels:
    app: my-nginx-deployment
spec:
  selector:
    matchLabels:
      app: my-nginx-pod
  replicas: 2
  template:
    metadata:
      labels:
        app: my-nginx-pod
    spec:
      containers:
      - name: my-nginx
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          limits:
            memory: "128Mi" #128 MB
            cpu: "100m" #100 millicpu (.1 cpu or 10% of the cpu)